[features]
seeds = false
skip-lint = false
[programs.localnet]
subscription = "EgYj5qqk1Kbq3eSwbUYwyDWQ6j3tnXkTej4MJJWkzqSQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ivmidable/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
