[features]
seeds = false
skip-lint = false
[programs.localnet]
deli = "7cr8PdkQzH1WoCk6gyrhHYJqXpGx3LZH7ttH1cxcD8MS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ivmidable/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
